module.exports={
    Publisher:require("./Publisher"),
    Author:require("./Author"),
    User:require("./User"),
    Book:require('./Book'),
    Category:require("./Category"),
    Borrower:require("./Borrower"),
    BookCopy:require("./BookCopy"),
    Loan:require("./Loan")
}